apiVersion: hive.openshift.io/v1
kind: SelectorSyncSet
metadata:
  labels:
    managed.openshift.io/gitHash: ${IMAGE_TAG}
    managed.openshift.io/gitRepoName: ${REPO_NAME}
    managed.openshift.io/osd: 'true'
  name: osd-serviceaccounts-aws
spec:
  clusterDeploymentSelector:
    matchLabels:
      api.openshift.com/managed: 'true'
      hive.openshift.io/cluster-platform: aws
    matchExpressions:
    - key: api.openshift.com/fedramp
      operator: NotIn
      values:
      - 'true'
  resourceApplyMode: Upsert
  resources:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: custom-domains-operator
      namespace: openshift-custom-domains-operator
