apiVersion: hive.openshift.io/v1
kind: SelectorSyncSet
metadata:
  labels:
    managed.openshift.io/gitHash: ${IMAGE_TAG}
    managed.openshift.io/gitRepoName: ${REPO_NAME}
    managed.openshift.io/osd: 'true'
  name: osd-hsts-routes-pre-4.11
spec:
  clusterDeploymentSelector:
    matchLabels:
      api.openshift.com/managed: 'true'
    matchExpressions:
    - key: hive.openshift.io/version-major-minor
      operator: In
      values:
      - '4.0'
      - '4.1'
      - '4.2'
      - '4.3'
      - '4.4'
      - '4.5'
      - '4.6'
      - '4.7'
      - '4.8'
      - '4.9'
      - '4.10'
  resourceApplyMode: Sync
  patches:
  - apiVersion: route.openshift.io/v1
    applyMode: Sync
    kind: Route
    name: grafana
    namespace: openshift-monitoring
    patch: '{"metadata":{"annotations":{"haproxy.router.openshift.io/hsts_header":"max-age=31536000;preload"}}}'
    patchType: merge
