apiVersion: hive.openshift.io/v1
kind: SelectorSyncSet
metadata:
  labels:
    managed.openshift.io/gitHash: ${IMAGE_TAG}
    managed.openshift.io/gitRepoName: ${REPO_NAME}
    managed.openshift.io/osd: 'true'
  name: osd-serviceaccounts
spec:
  clusterDeploymentSelector:
    matchLabels:
      api.openshift.com/managed: 'true'
    matchExpressions:
    - key: api.openshift.com/sts
      operator: NotIn
      values:
      - 'true'
    - key: api.openshift.com/fedramp
      operator: NotIn
      values:
      - 'true'
  resourceApplyMode: Upsert
  resources:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: cloud-ingress-operator
      namespace: openshift-cloud-ingress-operator
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: managed-upgrade-operator
      namespace: openshift-managed-upgrade-operator
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: configure-alertmanager-operator
      namespace: openshift-monitoring
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: rbac-permissions-operator
      namespace: openshift-rbac-permissions
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: splunk-forwarder-operator
      namespace: openshift-splunk-forwarder-operator
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: managed-velero-operator
      namespace: openshift-velero
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: ocm-agent-operator
      namespace: openshift-ocm-agent-operator
