apiVersion: hive.openshift.io/v1
kind: SelectorSyncSet
metadata:
  labels:
    managed.openshift.io/gitHash: ${IMAGE_TAG}
    managed.openshift.io/gitRepoName: ${REPO_NAME}
    managed.openshift.io/osd: 'true'
  name: osd-registry
spec:
  clusterDeploymentSelector:
    matchLabels:
      api.openshift.com/managed: 'true'
    matchExpressions:
    - key: hive.openshift.io/version-major-minor
      operator: NotIn
      values:
      - '4.0'
      - '4.1'
      - '4.2'
      - '4.3'
      - '4.4'
  resourceApplyMode: Sync
  patches:
  - apiVersion: imageregistry.operator.openshift.io/v1
    applyMode: AlwaysApply
    kind: Config
    name: cluster
    patch: '{"spec":{"defaultRoute":true,"affinity":{"nodeAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"preference":{"matchExpressions":[{"key":"node-role.kubernetes.io/infra","operator":"Exists"}]},"weight":1}]}},"tolerations":[{"effect":"NoSchedule","key":"node-role.kubernetes.io/infra","operator":"Exists"}]}}'
    patchType: merge
  - apiVersion: imageregistry.operator.openshift.io/v1
    applyMode: AlwaysApply
    kind: Config
    name: cluster
    patch: '{"spec":{"nodeSelector": null}}'
    patchType: merge
