apiVersion: hive.openshift.io/v1
kind: SelectorSyncSet
metadata:
  labels:
    managed.openshift.io/gitHash: ${IMAGE_TAG}
    managed.openshift.io/gitRepoName: ${REPO_NAME}
    managed.openshift.io/osd: 'true'
  name: backplane-lpsre-rhoc-addon-connectors-operator
spec:
  clusterDeploymentSelector:
    matchLabels:
      api.openshift.com/managed: 'true'
      api.openshift.com/addon-connectors-operator: 'true'
  resourceApplyMode: Sync
  resources:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: backplane-lpsre-rhoc-admins-project
    rules:
    - apiGroups:
      - ''
      resources:
      - pods/exec
      verbs:
      - create
    - apiGroups:
      - ''
      resources:
      - pods/portforward
      verbs:
      - create
    - apiGroups:
      - batch
      resources:
      - jobs
      - cronjobs
      verbs:
      - delete
      - deletecollection
    - apiGroups:
      - build.openshift.io
      resources:
      - builds
      verbs:
      - delete
      - deletecollection
    - apiGroups:
      - ''
      resources:
      - pods
      - pods/attach
      verbs:
      - create
    - apiGroups:
      - ''
      resources:
      - pods
      - pods/log
      verbs:
      - get
    - apiGroups:
      - ''
      resources:
      - pods
      verbs:
      - delete
    - apiGroups:
      - ''
      resources:
      - configmaps
      - persistentvolumeclaims
      verbs:
      - '*'
    - apiGroups:
      - operators.coreos.com
      resources:
      - installplans
      verbs:
      - patch
    - apiGroups:
      - policy
      resources:
      - poddisruptionbudgets
      verbs:
      - list
      - get
    - apiGroups:
      - apps
      resources:
      - statefulsets
      verbs:
      - list
      - get
    - apiGroups:
      - ''
      resources:
      - events
      verbs:
      - list
      - get
    - apiGroups:
      - ''
      resources:
      - endpoints
      verbs:
      - list
      - get
    - apiGroups:
      - tekton.dev
      resources:
      - '*'
      verbs:
      - '*'
  - apiVersion: managed.openshift.io/v1alpha1
    kind: SubjectPermission
    metadata:
      name: backplane-lpsre-rhoc-admins-project
      namespace: openshift-rbac-permissions
    spec:
      permissions:
      - clusterRoleName: backplane-lpsre-rhoc-admins-project
        namespacesAllowedRegex: (^redhat-openshift-connectors$)
      subjectKind: Group
      subjectName: system:serviceaccounts:openshift-backplane-lpsre
