apiVersion: hive.openshift.io/v1
kind: SelectorSyncSet
metadata:
  labels:
    managed.openshift.io/gitHash: ${IMAGE_TAG}
    managed.openshift.io/gitRepoName: ${REPO_NAME}
    managed.openshift.io/osd: 'true'
  name: osd-cluster-ready
spec:
  clusterDeploymentSelector:
    matchLabels:
      api.openshift.com/managed: 'true'
  resourceApplyMode: Sync
  resources:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: osd-cluster-ready
      namespace: openshift-monitoring
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: osd-cluster-ready
      namespace: openshift-monitoring
    rules:
    - apiGroups:
      - ''
      resources:
      - pods
      verbs:
      - get
      - list
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: osd-cluster-ready
      namespace: openshift-monitoring
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: osd-cluster-ready
    subjects:
    - kind: ServiceAccount
      name: osd-cluster-ready
      namespace: openshift-monitoring
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: osd-cluster-ready
      namespace: openshift-machine-api
    rules:
    - apiGroups:
      - machine.openshift.io
      resources:
      - machines
      verbs:
      - list
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: osd-cluster-ready
      namespace: openshift-machine-api
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: osd-cluster-ready
    subjects:
    - kind: ServiceAccount
      name: osd-cluster-ready
      namespace: openshift-monitoring
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: osd-cluster-ready
      namespace: openshift-config
    rules:
    - apiGroups:
      - ''
      resources:
      - secrets
      verbs:
      - list
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: osd-cluster-ready
      namespace: openshift-config
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: osd-cluster-ready
    subjects:
    - kind: ServiceAccount
      name: osd-cluster-ready
      namespace: openshift-monitoring
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: osd-cluster-ready
    rules:
    - apiGroups:
      - config.openshift.io
      resources:
      - clusterversions
      verbs:
      - get
    - apiGroups:
      - apps
      resources:
      - daemonsets
      - replicasets
      verbs:
      - list
      - get
    - apiGroups:
      - ''
      resources:
      - nodes
      - pods
      verbs:
      - list
    - apiGroups:
      - config.openshift.io
      resources:
      - clusteroperators
      verbs:
      - list
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: osd-cluster-ready
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: osd-cluster-ready
    subjects:
    - kind: ServiceAccount
      name: osd-cluster-ready
      namespace: openshift-monitoring
