apiVersion: hive.openshift.io/v1
kind: SelectorSyncSet
metadata:
  labels:
    managed.openshift.io/gitHash: ${IMAGE_TAG}
    managed.openshift.io/gitRepoName: ${REPO_NAME}
    managed.openshift.io/osd: 'true'
  name: backplane-mcg-mcg-osd
spec:
  clusterDeploymentSelector:
    matchLabels:
      api.openshift.com/managed: 'true'
      api.openshift.com/addon-mcg-osd: 'true'
  resourceApplyMode: Sync
  resources:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: backplane-mcg-osd-cr-admins
    rules:
    - apiGroups:
      - mcg.openshift.io
      resources:
      - managedmcgs
      verbs:
      - get
      - list
      - watch
      - patch
      - update
    - apiGroups:
      - noobaa.io
      resources:
      - namespacestores
      - noobaas
      verbs:
      - get
      - list
      - watch
      - patch
      - update
  - apiVersion: managed.openshift.io/v1alpha1
    kind: SubjectPermission
    metadata:
      name: backplane-mcg-mcg-osd-admins
      namespace: openshift-rbac-permissions
    spec:
      permissions:
      - clusterRoleName: admin
        namespacesAllowedRegex: (^redhat-data-federation$)
      - clusterRoleName: backplane-mcg-osd-cr-admins
        namespacesAllowedRegex: (^redhat-data-federation$)
      subjectKind: Group
      subjectName: system:serviceaccounts:openshift-backplane-mcg
