apiVersion: hive.openshift.io/v1
kind: SelectorSyncSet
metadata:
  labels:
    managed.openshift.io/gitHash: ${IMAGE_TAG}
    managed.openshift.io/gitRepoName: ${REPO_NAME}
    managed.openshift.io/osd: 'true'
  name: backplane-srep-hypershift-management-cluster
spec:
  clusterDeploymentSelector:
    matchLabels:
      api.openshift.com/managed: 'true'
    matchExpressions:
    - key: ext-hypershift.openshift.io/cluster-type
      operator: In
      values:
      - management-cluster
    - key: api.openshift.com/fedramp
      operator: NotIn
      values:
      - 'true'
  resourceApplyMode: Sync
  resources:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: backplane-srep-management-cluster-cluster
    rules:
    - apiGroups:
      - work.open-cluster-management.io
      resources:
      - appliedmanifestworks
      verbs:
      - get
      - list
      - watch
    - apiGroups:
      - cluster.open-cluster-management.io
      resources:
      - clusterclaims
      verbs:
      - get
      - list
      - watch
    - apiGroups:
      - operator.open-cluster-management.io
      resources:
      - klusterlets
      verbs:
      - get
      - list
      - watch
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: backplane-srep-management-cluster-project
    rules:
    - apiGroups:
      - policy.open-cluster-management.io
      resources:
      - policies
      - configurationpolicies
      verbs:
      - get
      - list
      - watch
    - apiGroups:
      - hypershift.openshift.io
      resources:
      - awsendpointservices
      - hostedclusters
      - hostedcontrolplanes
      - nodepools
      verbs:
      - get
      - list
      - watch
    - apiGroups:
      - cluster.x-k8s.io
      resources:
      - clusterclasses
      - clusters
      - machinedeployments
      - machinehealthchecks
      - machinepools
      - machines
      - machinesets
      verbs:
      - get
      - list
      - watch
    - apiGroups:
      - infrastructure.cluster.x-k8s.io
      resources:
      - awsclustercontrolleridentities
      - awsclusterroleidentities
      - awsclusters
      - awsclusterstaticidentities
      - awsclustertemplates
      - awsfargateprofiles
      - awsmachinepools
      - awsmachines
      - awsmachinetemplates
      - awsmanagedmachinepools
      - azureclusteridentities
      - azureclusters
      - azuremachines
      - azuremachinetemplates
      - ibmpowervsclusters
      - ibmpowervsimages
      - ibmpowervsmachines
      - ibmpowervsmachinetemplates
      - ibmvpcclusters
      - ibmvpcmachines
      - ibmvpcmachinetemplates
      - kubevirtclusters
      - kubevirtmachines
      - kubevirtmachinetemplates
      verbs:
      - get
      - list
      - watch
    - apiGroups:
      - package-operator.run
      resources:
      - '*'
      verbs:
      - get
      - list
      - watch
  - apiVersion: managed.openshift.io/v1alpha1
    kind: SubjectPermission
    metadata:
      name: backplane-srep-management-cluster
      namespace: openshift-rbac-permissions
    spec:
      permissions:
      - clusterRoleName: backplane-srep-management-cluster-project
        namespacesAllowedRegex: (^uhc.*|^ocm.*|^klusterlet.*)
      - clusterRoleName: dedicated-readers
        namespacesAllowedRegex: (^hypershift.*|^uhc.*|^ocm.*|^klusterlet.*|^open-cluster-management.*)
      subjectKind: Group
      subjectName: system:serviceaccounts:openshift-backplane-srep
