apiVersion: hive.openshift.io/v1
kind: SelectorSyncSet
metadata:
  labels:
    managed.openshift.io/gitHash: ${IMAGE_TAG}
    managed.openshift.io/gitRepoName: ${REPO_NAME}
    managed.openshift.io/osd: 'true'
  name: backplane-srep
spec:
  clusterDeploymentSelector:
    matchLabels:
      api.openshift.com/managed: 'true'
  resourceApplyMode: Sync
  resources:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: openshift-backplane-srep
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: backplane-srep-admins-cluster
    rules:
    - apiGroups:
      - ''
      resources:
      - nodes
      verbs:
      - patch
    - apiGroups:
      - ''
      resources:
      - nodes/proxy
      verbs:
      - get
    - apiGroups:
      - config.openshift.io
      resources:
      - projects
      verbs:
      - '*'
    - apiGroups:
      - project.openshift.io
      resources:
      - projects
      - projectrequests
      verbs:
      - '*'
    - apiGroups:
      - ''
      resources:
      - namespaces
      - namespaces/finalize
      verbs:
      - '*'
    - apiGroups:
      - certificates.k8s.io
      resources:
      - certificatesigningrequests/approval
      verbs:
      - update
    - nonResourceURLs:
      - '*'
      verbs:
      - '*'
    - apiGroups:
      - authentication.k8s.io
      resources:
      - tokenreviews
      verbs:
      - create
    - apiGroups:
      - authorization.k8s.io
      resources:
      - localsubjectaccessreviews
      - selfsubjectaccessreviews
      - selfsubjectrulesreviews
      - subjectaccessreviews
      verbs:
      - create
    - apiGroups:
      - ''
      - authorization.openshift.io
      resources:
      - localresourceaccessreviews
      - localsubjectaccessreviews
      - resourceaccessreviews
      - selfsubjectrulesreviews
      - subjectaccessreviews
      - subjectrulesreviews
      verbs:
      - create
    - apiGroups:
      - user.openshift.io
      resources:
      - users
      - identities
      verbs:
      - delete
      - deletecollection
    - apiGroups:
      - machineconfiguration.openshift.io
      resources:
      - '*'
      verbs:
      - get
      - list
      - watch
    - apiGroups:
      - machine.openshift.io
      resources:
      - '*'
      verbs:
      - get
      - list
      - watch
    - apiGroups:
      - machine.openshift.io
      resources:
      - machines
      verbs:
      - delete
    - apiGroups:
      - apiserver.openshift.io
      resources:
      - apirequestcounts
      verbs:
      - get
      - list
      - watch
    - apiGroups:
      - certificates.k8s.io
      resources:
      - certificatesigningrequests
      verbs:
      - get
      - list
      - watch
      - delete
    - apiGroups:
      - avo.openshift.io
      resources:
      - vpcendpoints
      verbs:
      - get
      - list
      - watch
      - delete
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: backplane-srep-admins-project
    rules:
    - apiGroups:
      - ''
      resources:
      - pods/eviction
      verbs:
      - create
    - apiGroups:
      - ''
      resources:
      - pods/portforward
      verbs:
      - create
    - apiGroups:
      - ''
      resources:
      - pods/exec
      verbs:
      - create
    - apiGroups:
      - batch
      resources:
      - jobs
      verbs:
      - delete
      - deletecollection
      - create
    - apiGroups:
      - build.openshift.io
      resources:
      - builds
      verbs:
      - delete
      - deletecollection
    - apiGroups:
      - ''
      resources:
      - pods
      - pods/attach
      verbs:
      - create
    - apiGroups:
      - ''
      resources:
      - pods
      verbs:
      - delete
      - deletecollection
    - apiGroups:
      - security.openshift.io
      resources:
      - podsecuritypolicyreviews
      - podsecuritypolicyselfsubjectreviews
      - podsecuritypolicysubjectreviews
      verbs:
      - create
    - apiGroups:
      - authorization.openshift.io
      resources:
      - localresourceaccessreviews
      - localsubjectaccessreviews
      verbs:
      - create
    - apiGroups:
      - logging.openshift.io
      resources:
      - '*'
      verbs:
      - '*'
    - apiGroups:
      - velero.io
      resources:
      - backups
      verbs:
      - create
    - apiGroups:
      - velero.io
      resources:
      - deletebackuprequests
      - downloadrequests
      - serverstatusrequests
      verbs:
      - '*'
    - apiGroups:
      - velero.io
      resources:
      - '*'
      verbs:
      - get
      - list
      - watch
    - apiGroups:
      - ''
      resources:
      - persistentvolumeclaims
      verbs:
      - delete
      - patch
    - apiGroups:
      - ''
      resources:
      - replicationcontrollers/scale
      verbs:
      - patch
    - apiGroups:
      - apps
      resources:
      - deployments/scale
      - replicasets/scale
      - statefulsets/scale
      verbs:
      - patch
    - apiGroups:
      - apps.openshift.io
      resources:
      - deploymentconfigs/scale
      verbs:
      - patch
    - apiGroups:
      - ''
      resources:
      - replicasets
      verbs:
      - delete
      - deletecollection
    - apiGroups:
      - machine.openshift.io
      resources:
      - machinehealthchecks
      verbs:
      - patch
    - apiGroups:
      - machine.openshift.io
      resources:
      - machinesets/scale
      verbs:
      - patch
    - apiGroups:
      - monitoring.coreos.com
      resources:
      - prometheuses
      verbs:
      - patch
    - apiGroups:
      - upgrade.managed.openshift.io
      resources:
      - upgradeconfigs
      verbs:
      - delete
    - apiGroups:
      - operators.coreos.com
      resources:
      - clusterserviceversions
      - installplans
      - subscriptions
      verbs:
      - delete
    - apiGroups:
      - monitoring.coreos.com
      resources:
      - '*'
      verbs:
      - get
      - list
      - watch
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: backplane-srep-mustgather
      namespace: openshift-must-gather-operator
    rules:
    - apiGroups:
      - ''
      resources:
      - secrets
      verbs:
      - create
    - apiGroups:
      - managed.openshift.io
      resources:
      - mustgathers
      verbs:
      - create
      - delete
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: backplane-srep-mustgather
      namespace: openshift-must-gather-operator
    subjects:
    - apiGroup: rbac.authorization.k8s.io
      kind: Group
      name: system:serviceaccounts:openshift-backplane-srep
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: backplane-srep-mustgather
  - apiVersion: managed.openshift.io/v1alpha1
    kind: SubjectPermission
    metadata:
      name: backplane-srep
      namespace: openshift-rbac-permissions
    spec:
      clusterPermissions:
      - backplane-srep-admins-cluster
      - backplane-readers-cluster
      permissions:
      - clusterRoleName: backplane-srep-admins-project
        namespacesAllowedRegex: (^kube$|^kube-.*|^openshift$|^openshift-.*|^default$|^redhat-.*)
        namespacesDeniedRegex: openshift-backplane-cluster-admin
      - clusterRoleName: dedicated-readers
        namespacesAllowedRegex: (^kube$|^kube-.*|^openshift$|^openshift-.*|^default$|^redhat-.*)
        namespacesDeniedRegex: openshift-backplane-cluster-admin
      subjectKind: Group
      subjectName: system:serviceaccounts:openshift-backplane-srep
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: backplane-srep-pcap-collector
      namespace: openshift-backplane-managed-scripts
    rules:
    - verbs:
      - create
      - delete
      apiGroups:
      - ''
      resources:
      - secrets
      resourceNames:
      - pcap-collector-creds
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: backplane-srep-mustgather
      namespace: openshift-backplane-managed-scripts
    subjects:
    - apiGroup: rbac.authorization.k8s.io
      kind: Group
      name: system:serviceaccounts:openshift-backplane-srep
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: backplane-srep-pcap-collector
