apiVersion: hive.openshift.io/v1
kind: SelectorSyncSet
metadata:
  labels:
    managed.openshift.io/gitHash: ${IMAGE_TAG}
    managed.openshift.io/gitRepoName: ${REPO_NAME}
    managed.openshift.io/osd: 'true'
  name: sre-pruning-images
spec:
  clusterDeploymentSelector:
    matchLabels:
      api.openshift.com/managed: 'true'
    matchExpressions:
    - key: hive.openshift.io/version-major-minor
      operator: NotIn
      values:
      - '4.0'
      - '4.1'
      - '4.2'
      - '4.3'
      - '4.4'
      - '4.5'
  resourceApplyMode: Sync
  patches:
  - apiVersion: imageregistry.operator.openshift.io/v1
    applyMode: AlwaysApply
    kind: ImagePruner
    name: cluster
    namespace: openshift-image-registry
    patch: '{"spec":{"keepYoungerThan":86400000000000, "ignoreInvalidImageReferences":
      true, "schedule": "0 */1 * * *", "suspend": false, "affinity": {"nodeAffinity":
      {"preferredDuringSchedulingIgnoredDuringExecution": [{"preference": {"matchExpressions":
      [{"key": "node-role.kubernetes.io/infra", "operator": "Exists"}]}, "weight":
      1}]}}, "tolerations": [{"effect": "NoSchedule", "key": "node-role.kubernetes.io/infra",
      "operator": "Exists"}]}}'
    patchType: merge
