apiVersion: hive.openshift.io/v1
kind: SelectorSyncSet
metadata:
  labels:
    managed.openshift.io/gitHash: ${IMAGE_TAG}
    managed.openshift.io/gitRepoName: ${REPO_NAME}
    managed.openshift.io/osd: 'true'
  name: managed-velero-operator-rolebinding
spec:
  clusterDeploymentSelector:
    matchLabels:
      api.openshift.com/managed: 'true'
  resourceApplyMode: Sync
  resources:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      creationTimestamp: null
      name: cluster-config-v1-reader
      namespace: kube-system
    rules:
    - apiGroups:
      - ''
      resourceNames:
      - cluster-config-v1
      resources:
      - configmaps
      verbs:
      - get
  - kind: RoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: managed-velero-operator-cluster-config-v1-reader
      namespace: kube-system
      labels:
        owner: managed-velero-operator
        owner.namespace: managed-velero-operator
    subjects:
    - kind: ServiceAccount
      name: managed-velero-operator
      namespace: openshift-velero
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: cluster-config-v1-reader
