apiVersion: hive.openshift.io/v1
kind: SelectorSyncSet
metadata:
  labels:
    managed.openshift.io/gitHash: ${IMAGE_TAG}
    managed.openshift.io/gitRepoName: ${REPO_NAME}
    managed.openshift.io/osd: 'true'
  name: osd-codeready-workspaces
spec:
  clusterDeploymentSelector:
    matchLabels:
      api.openshift.com/managed: 'true'
  resourceApplyMode: Sync
  resources:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: openshift-codeready-workspaces
      annotations:
        openshift.io/node-selector: ''
      labels:
        openshift.io/cluster-logging: 'true'
        openshift.io/cluster-monitoring: 'true'
  - apiVersion: operators.coreos.com/v1
    kind: OperatorGroup
    metadata:
      name: openshift-codeready-workspaces
      namespace: openshift-codeready-workspaces
    spec:
      serviceAccount:
        metadata:
          creationTimestamp: null
      targetNamespaces:
      - openshift-codeready-workspaces
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: dedicated-admins-openshift-codeready-workspaces
      namespace: openshift-codeready-workspaces
    rules:
    - apiGroups:
      - ''
      resources:
      - namespaces
      - pods
      - pods/log
      - events
      verbs:
      - list
      - get
      - watch
    - apiGroups:
      - operators.coreos.com
      resources:
      - subscriptions
      - clusterserviceversions
      verbs:
      - '*'
    - apiGroups:
      - ''
      resources:
      - configmaps
      verbs:
      - list
    - apiGroups:
      - org.eclipse.che
      resources:
      - '*'
      verbs:
      - '*'
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: dedicated-admins-openshift-codeready-workspaces
      namespace: openshift-codeready-workspaces
    subjects:
    - kind: Group
      name: dedicated-admins
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: dedicated-admins-openshift-codeready-workspaces
