apiVersion: hive.openshift.io/v1
kind: SelectorSyncSet
metadata:
  labels:
    managed.openshift.io/gitHash: ${IMAGE_TAG}
    managed.openshift.io/gitRepoName: ${REPO_NAME}
    managed.openshift.io/osd: 'true'
  name: osd-cluster-acks-sts-4.9
spec:
  clusterDeploymentSelector:
    matchLabels:
      api.openshift.com/managed: 'true'
    matchExpressions:
    - key: hive.openshift.io/version-major-minor
      operator: In
      values:
      - '4.8'
    - key: api.openshift.com/gate-sts
      operator: In
      values:
      - '4.9'
    - key: api.openshift.com/sts
      operator: In
      values:
      - 'true'
  resourceApplyMode: Sync
  patches:
  - apiVersion: operator.openshift.io/v1
    kind: CloudCredential
    name: cluster
    applyMode: AlwaysApply
    patch: '{"metadata":{"annotations":{"cloudcredential.openshift.io/upgradeable-to":"v4.9"}}}'
    patchType: merge
