apiVersion: hive.openshift.io/v1
kind: SelectorSyncSet
metadata:
  labels:
    managed.openshift.io/gitHash: ${IMAGE_TAG}
    managed.openshift.io/gitRepoName: ${REPO_NAME}
    managed.openshift.io/osd: 'true'
  name: osd-strimzi-operator
spec:
  clusterDeploymentSelector:
    matchLabels:
      api.openshift.com/managed: 'true'
  resourceApplyMode: Sync
  resources:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: openshift-strimzi
      annotations:
        openshift.io/node-selector: ''
      labels:
        openshift.io/cluster-logging: 'true'
  - apiVersion: operators.coreos.com/v1
    kind: OperatorGroup
    metadata:
      name: openshift-strimzi
      namespace: openshift-strimzi
    spec:
      serviceAccount:
        metadata:
          creationTimestamp: null
      targetNamespaces:
      - openshift-strimzi
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: dedicated-admins-openshift-strimzi
      namespace: openshift-strimzi
    rules:
    - apiGroups:
      - ''
      resources:
      - namespaces
      - pods
      - pods/log
      - events
      verbs:
      - list
      - get
      - watch
    - apiGroups:
      - operators.coreos.com
      resources:
      - subscriptions
      - clusterserviceversions
      verbs:
      - '*'
    - apiGroups:
      - monitoring.coreos.com
      resources:
      - prometheusrules
      - servicemonitors
      - podmonitors
      verbs:
      - '*'
    - apiGroups:
      - ''
      resources:
      - secrets
      verbs:
      - create
      - update
      - get
      - list
      - watch
      - delete
    - apiGroups:
      - ''
      resources:
      - configmaps
      verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    - apiGroups:
      - kafka.strimzi.io
      resources:
      - '*'
      verbs:
      - '*'
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: dedicated-admins-openshift-strimzi
      namespace: openshift-strimzi
    subjects:
    - kind: Group
      name: dedicated-admins
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: dedicated-admins-openshift-strimzi
