apiVersion: hive.openshift.io/v1
kind: SelectorSyncSet
metadata:
  labels:
    managed.openshift.io/gitHash: ${IMAGE_TAG}
    managed.openshift.io/gitRepoName: ${REPO_NAME}
    managed.openshift.io/osd: 'true'
  name: osd-custom-domains
spec:
  clusterDeploymentSelector:
    matchLabels:
      api.openshift.com/managed: 'true'
  resourceApplyMode: Sync
  resources:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      labels:
        managed.openshift.io/aggregate-to-dedicated-admins: cluster
      name: osd-custom-domains-dedicated-admin-cluster
    rules:
    - apiGroups:
      - managed.openshift.io
      resources:
      - customdomains
      verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
