apiVersion: hive.openshift.io/v1
kind: SelectorSyncSet
metadata:
  labels:
    managed.openshift.io/gitHash: ${IMAGE_TAG}
    managed.openshift.io/gitRepoName: ${REPO_NAME}
    managed.openshift.io/osd: 'true'
  name: backplane-cse
spec:
  clusterDeploymentSelector:
    matchLabels:
      api.openshift.com/managed: 'true'
  resourceApplyMode: Sync
  resources:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: openshift-backplane-cse
  - apiVersion: managed.openshift.io/v1alpha1
    kind: SubjectPermission
    metadata:
      name: backplane-cse
      namespace: openshift-rbac-permissions
    spec:
      clusterPermissions:
      - backplane-readers-cluster
      permissions:
      - clusterRoleName: dedicated-readers
        namespacesAllowedRegex: (^kube$|^kube-.*|^openshift$|^openshift-.*|^default$|^redhat-.*)
        namespacesDeniedRegex: openshift-backplane-cluster-admin
      subjectKind: Group
      subjectName: system:serviceaccounts:openshift-backplane-cse
