apiVersion: hive.openshift.io/v1
kind: SelectorSyncSet
metadata:
  labels:
    managed.openshift.io/gitHash: ${IMAGE_TAG}
    managed.openshift.io/gitRepoName: ${REPO_NAME}
    managed.openshift.io/osd: 'true'
  name: osd-openshift-operators-redhat
spec:
  clusterDeploymentSelector:
    matchLabels:
      api.openshift.com/managed: 'true'
  resourceApplyMode: Sync
  resources:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: openshift-operators-redhat
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: admin-dedicated-admins
      namespace: openshift-operators-redhat
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: admin
    subjects:
    - apiGroup: rbac.authorization.k8s.io
      kind: Group
      name: dedicated-admins
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: admin-system:serviceaccounts:dedicated-admin
      namespace: openshift-operators-redhat
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: admin
    subjects:
    - apiGroup: rbac.authorization.k8s.io
      kind: Group
      name: system:serviceaccounts:dedicated-admin
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: openshift-operators-redhat-dedicated-admins
      namespace: openshift-operators-redhat
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: dedicated-admins-project
    subjects:
    - apiGroup: rbac.authorization.k8s.io
      kind: Group
      name: dedicated-admins
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: openshift-operators-redhat:serviceaccounts:dedicated-admin
      namespace: openshift-operators-redhat
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: dedicated-admins-project
    subjects:
    - apiGroup: rbac.authorization.k8s.io
      kind: Group
      name: system:serviceaccounts:dedicated-admin
