apiVersion: hive.openshift.io/v1
kind: SelectorSyncSet
metadata:
  labels:
    managed.openshift.io/gitHash: ${IMAGE_TAG}
    managed.openshift.io/gitRepoName: ${REPO_NAME}
    managed.openshift.io/osd: 'true'
  name: backplane-elevated-sre
spec:
  clusterDeploymentSelector:
    matchLabels:
      api.openshift.com/managed: 'true'
  resourceApplyMode: Sync
  resources:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: backplane-impersonate-cluster-admin
    rules:
    - apiGroups:
      - ''
      resources:
      - users
      verbs:
      - impersonate
      resourceNames:
      - backplane-cluster-admin
    - apiGroups:
      - authentication.k8s.io
      verbs:
      - impersonate
      resources:
      - userextras/reason
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: backplane-impersonate-cluster-admin
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: backplane-impersonate-cluster-admin
    subjects:
    - kind: Group
      name: system:serviceaccounts:openshift-backplane-srep
    - kind: Group
      name: system:serviceaccounts:openshift-backplane-cssre
  - apiVersion: user.openshift.io/v1
    kind: User
    metadata:
      name: backplane-cluster-admin
    groups: []
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: backplane-cluster-admin
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: cluster-admin
    subjects:
    - kind: User
      name: backplane-cluster-admin
