apiVersion: hive.openshift.io/v1
kind: SelectorSyncSet
metadata:
  labels:
    managed.openshift.io/gitHash: ${IMAGE_TAG}
    managed.openshift.io/gitRepoName: ${REPO_NAME}
    managed.openshift.io/osd: 'true'
  name: osd-scanning
spec:
  clusterDeploymentSelector:
    matchLabels:
      api.openshift.com/managed: 'true'
    matchExpressions:
    - key: api.openshift.com/fedramp
      operator: In
      values:
      - 'true'
  resourceApplyMode: Sync
  resources:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: openshift-scanning
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: logger-sa
      namespace: openshift-scanning
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: scanner-sa
      namespace: openshift-scanning
  - kind: SecurityContextConstraints
    apiVersion: security.openshift.io/v1
    metadata:
      name: osd-scanning-scc
    allowPrivilegedContainer: true
    allowHostNetwork: false
    allowedCapabilities:
    - NET_ADMIN
    - NET_RAW
    runAsUser:
      type: RunAsAny
    seLinuxContext:
      type: RunAsAny
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      creationTimestamp: null
      name: logger-clusterrole
      namespace: openshift-scanning
    rules:
    - apiGroups:
      - ''
      resources:
      - pods
      - pods/status
      - namespaces
      - services
      verbs:
      - get
      - list
    - apiGroups:
      - config.openshift.io
      resources:
      - clusterversions
      verbs:
      - get
      - list
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: logger-clusterrolebinding
      namespace: openshift-scanning
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: logger-clusterrole
    subjects:
    - kind: ServiceAccount
      name: logger-sa
      namespace: openshift-scanning
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      creationTimestamp: null
      name: scanner-role
      namespace: openshift-scanning
    rules:
    - apiGroups:
      - security.openshift.io
      resources:
      - securitycontextconstraints
      verbs:
      - use
    - apiGroups:
      - security.openshift.io
      resourceNames:
      - privileged
      resources:
      - securitycontextconstraints
      verbs:
      - use
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: scanner-rolebinding
      namespace: openshift-scanning
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: scanner-role
    subjects:
    - kind: ServiceAccount
      name: scanner-sa
      namespace: openshift-scanning
  - apiVersion: apps/v1
    kind: DaemonSet
    metadata:
      name: logger
      namespace: openshift-scanning
    spec:
      selector:
        matchLabels:
          name: logger
      template:
        metadata:
          labels:
            name: logger
        spec:
          containers:
          - env:
            - name: OO_PAUSE_ON_START
              value: 'false'
            - name: LOG_WRITER_URL
              value: http://logger.openshift-scanning.svc:8443/api/log
            - name: SCAN_LOG_FILE
              value: /host/var/log/openshift_managed_malware_scan.log
            - name: POD_LOG_FILE
              value: /host/var/log/openshift_managed_pod_creation.log
            - name: POD_SOCK
              value: '@rpc.pod.sock'
            - name: SCAN_SOCK
              value: '@rpc.scan.sock'
            - name: APP_SECRETS_PATH
              value: /secrets/api_config.json
            - name: SA_TOKEN_PATH
              value: /var/run/secrets/kubernetes.io/serviceaccount/token
            - name: OAPI_URL
              value: https://openshift.default.svc.cluster.local
            - name: CV_URL
              value: /apis/config.openshift.io/v1/clusterversions
            - name: MIDDLEWARE_LOGGER
              value: 'true'
            - name: LISTEN_PORT
              value: '8443'
            - name: TLS_CERT_FILE
              value: /certs/tls.crt
            - name: TLS_KEY_FILE
              value: /certs/tls.key
            image: quay.io/app-sre/pod-logger@sha256:0e1eb7df212641a5bd6c6655ad9e613f59cee32fd0075e5c46df6fe88cab025e
            name: logger
            ports:
            - containerPort: 8443
              name: logger
              protocol: TCP
            resources:
              limits:
                cpu: 100m
                memory: 100Mi
              requests:
                cpu: 100m
                memory: 50Mi
            volumeMounts:
            - mountPath: /secrets
              name: logger-secrets
            - mountPath: /certs
              name: logger-certs
          - env:
            - name: OO_PAUSE_ON_START
              value: 'false'
            - name: SOCK
              value: '@rpc.pod.sock'
            image: quay.io/app-sre/log-printer@sha256:9e04ed57a497243ad54bc8f432eab0da8958f710baa92c11fdb77e27498a199e
            name: pod-printer
            resources:
              limits:
                cpu: 100m
                memory: 100Mi
              requests:
                cpu: 100m
                memory: 50Mi
          - env:
            - name: OO_PAUSE_ON_START
              value: 'false'
            - name: SOCK
              value: '@rpc.scan.sock'
            image: quay.io/app-sre/log-printer@sha256:9e04ed57a497243ad54bc8f432eab0da8958f710baa92c11fdb77e27498a199e
            name: scan-printer
            resources:
              limits:
                cpu: 100m
                memory: 100Mi
              requests:
                cpu: 100m
                memory: 50Mi
          nodeSelector:
            node-role.kubernetes.io/master: ''
          serviceAccountName: logger-sa
          tolerations:
          - operator: Exists
          volumes:
          - name: logger-secrets
            secret:
              secretName: logger-secrets
          - name: logger-certs
            secret:
              secretName: loggerservice
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        k8s-app: loggerservice
        name: loggerservice
      name: loggerservice
      namespace: openshift-scanning
      annotations:
        service.beta.openshift.io/serving-cert-secret-name: loggerservice
    spec:
      ports:
      - name: loggerservice
        port: 8443
        protocol: TCP
        targetPort: 8443
      selector:
        name: logger
  - apiVersion: apps/v1
    kind: DaemonSet
    metadata:
      name: scanner
      namespace: openshift-scanning
    spec:
      selector:
        matchLabels:
          name: scanner
      template:
        metadata:
          labels:
            name: scanner
        spec:
          containers:
          - env:
            - name: OO_PAUSE_ON_START
              value: 'false'
            - name: CLAM_DB_DIRECTORY
              value: /clam
            - name: DEBUG_SECRETS
              value: 'false'
            - name: CLAM_SECRETS_FILE
              value: /secrets/clam_update_config.json
            image: quay.io/app-sre/clamsig-puller@sha256:9ffe2d6573d097bd990477bca9fcce9c0a88e79b873fd093585677985913a235
            name: clamsig-puller
            resources:
              limits:
                cpu: 100m
                memory: 2Gi
              requests:
                cpu: 100m
                memory: 500Mi
            volumeMounts:
            - mountPath: /secrets
              name: clam-secrets
            - mountPath: /clam
              name: clam-files
          - env:
            - name: OO_PAUSE_ON_START
              value: 'false'
            image: quay.io/app-sre/clamd@sha256:dd039548cfac5bc9d494a934b071f36c311afd0554eb41343d39dad52c3ff6d3
            name: clamd
            resources:
              limits:
                cpu: 300m
                memory: 3Gi
              requests:
                cpu: 100m
                memory: 800Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
            volumeMounts:
            - mountPath: /var/lib/clamav
              name: clam-files
          - env:
            - name: OO_PAUSE_ON_START
              value: 'false'
            - name: CHROOT_PATH
              value: /host
            image: quay.io/app-sre/container-info@sha256:234f31c832396529c129f82d55d197483f36074403a60fa36e7cf9b89564b30e
            name: info
            resources:
              limits:
                cpu: 100m
                memory: 50Mi
              requests:
                cpu: 100m
                memory: 20Mi
            securityContext:
              privileged: true
              runAsUser: 0
            volumeMounts:
            - mountPath: /clam
              name: clam-files
            - mountPath: /host
              name: host-filesystem
          - env:
            - name: OO_PAUSE_ON_START
              value: 'false'
            - name: ACTIVE_SCAN
              value: 'true'
            - name: CRIO_LOG_URL
              value: https://loggerservice.openshift-scanning.svc.cluster.local:8443/api/crio/log
            - name: DOCKER_LOG_URL
              value: https://loggerservice.openshift-scanning.svc.cluster.local:8443/api/docker/log
            - name: CLAM_LOG_URL
              value: https://loggerservice.openshift-scanning.svc.cluster.local:8443/api/clam/scanresult
            - name: JOURNAL_PATH
              value: /var/log/journal
            - name: SCAN_RESULTS_DIR
            - name: POST_RESULT_URL
              value: https://loggerservice.openshift-scanning.svc.cluster.local:8443/api/clam/scanresult
            - name: OUT_FILE
            - name: SKIP_NAMESPACE_PREFIXES
              value: openshift-
            - name: SKIP_NAMESPACES
              value: openshift-scanning,ci
            - name: CLAM_SOCKET
              value: /clam/clamd.sock
            - name: INFO_SOCKET
              value: '@rpc.sock'
            image: quay.io/app-sre/watcher@sha256:e91059d2045f91643beb2f146a6015bec8bbd4ff0cbe19970dc631cacf3368b0
            name: watcher
            resources:
              limits:
                cpu: 100m
                memory: 100Mi
              requests:
                cpu: 100m
                memory: 50Mi
            securityContext:
              privileged: true
              runAsUser: 0
            volumeMounts:
            - mountPath: /secrets
              name: clam-secrets
            - mountPath: /var/log/journal
              name: watcher-host-journal
            - mountPath: /host
              name: host-filesystem
            - mountPath: /clam
              name: clam-files
          - env:
            - name: OO_PAUSE_ON_START
              value: 'false'
            - name: CRIO_LOG_URL
              value: https://loggerservice.openshift-scanning.svc.cluster.local:8443/api/crio/log
            - name: DOCKER_LOG_URL
              value: https://loggerservice.openshift-scanning.svc.cluster.local:8443/api/docker/log
            - name: CLAM_LOG_URL
              value: https://loggerservice.openshift-scanning.svc.cluster.local:8443/api/clam/scanresult
            - name: JOURNAL_PATH
              value: /var/log/journal
            - name: SCAN_RESULTS_DIR
            - name: POST_RESULT_URL
              value: https://loggerservice.openshift-scanning.svc.cluster.local:8443/api/clam/scanresult
            - name: OUT_FILE
            - name: CLAM_SOCKET
              value: /clam/clamd.sock
            - name: INFO_SOCKET
              value: '@rpc.sock'
            - name: SCHEDULED_SCAN
              value: 'true'
            - name: SCHEDULED_SCAN_DAY
              value: Saturday
            - name: MIN_CON_DAY
              value: '0'
            - name: SKIP_NAMESPACE_PREFIXES
              value: openshift-
            - name: SKIP_NAMESPACES
              value: openshift-scanning
            - name: HOST_SCAN_DIRS
              value: /host
            image: quay.io/app-sre/watcher@sha256:e91059d2045f91643beb2f146a6015bec8bbd4ff0cbe19970dc631cacf3368b0
            name: scheduler
            resources:
              limits:
                cpu: 100m
                memory: 100Mi
              requests:
                cpu: 100m
                memory: 50Mi
            securityContext:
              privileged: true
              runAsUser: 0
            volumeMounts:
            - mountPath: /var/log/journal
              name: watcher-host-journal
            - mountPath: /host
              name: host-filesystem
            - mountPath: /clam
              name: clam-files
          dnsPolicy: ClusterFirst
          initContainers:
          - env:
            - name: OO_PAUSE_ON_START
              value: 'false'
            - name: INIT_CONTAINER
              value: 'true'
            - name: CLAM_DB_DIRECTORY
              value: /clam
            - name: DEBUG_SECRETS
              value: 'false'
            - name: CLAM_SECRETS_FILE
              value: /secrets/clam_update_config.json
            image: quay.io/app-sre/clamsig-puller@sha256:9ffe2d6573d097bd990477bca9fcce9c0a88e79b873fd093585677985913a235
            name: init-clamsig-puller
            resources:
              limits:
                cpu: 100m
                memory: 2Gi
              requests:
                cpu: 100m
                memory: 50Mi
            volumeMounts:
            - mountPath: /secrets
              name: clam-secrets
            - mountPath: /clam
              name: clam-files
          nodeSelector:
            kubernetes.io/os: linux
          serviceAccountName: scanner-sa
          tolerations:
          - operator: Exists
          volumes:
          - name: clam-secrets
            secret:
              secretName: clam-secrets
          - emptyDir: {}
            name: clam-files
          - hostPath:
              path: /
              type: ''
            name: host-filesystem
          - hostPath:
              path: /var/log/journal
              type: ''
            name: watcher-host-journal
