apiVersion: hive.openshift.io/v1
kind: SelectorSyncSet
metadata:
  labels:
    managed.openshift.io/gitHash: ${IMAGE_TAG}
    managed.openshift.io/gitRepoName: ${REPO_NAME}
    managed.openshift.io/osd: 'true'
  name: backplane-addon-connectors-addon-connectors
spec:
  clusterDeploymentSelector:
    matchLabels:
      api.openshift.com/managed: 'true'
      api.openshift.com/addon-connectors-operator: 'true'
  resourceApplyMode: Sync
  resources:
  - apiVersion: managed.openshift.io/v1alpha1
    kind: SubjectPermission
    metadata:
      name: backplane-addon-connectors-admins
      namespace: openshift-rbac-permissions
    spec:
      permissions:
      - clusterRoleName: admin
        namespacesAllowedRegex: (^redhat-openshift-connectors.*$)
      subjectKind: Group
      subjectName: system:serviceaccounts:openshift-backplane-addon-connectors
