apiVersion: hive.openshift.io/v1
kind: SelectorSyncSet
metadata:
  labels:
    managed.openshift.io/gitHash: ${IMAGE_TAG}
    managed.openshift.io/gitRepoName: ${REPO_NAME}
    managed.openshift.io/osd: 'true'
  name: osd-route-monitor-operator
spec:
  clusterDeploymentSelector:
    matchLabels:
      api.openshift.com/managed: 'true'
    matchExpressions:
    - key: api.openshift.com/fedramp
      operator: NotIn
      values:
      - 'true'
  resourceApplyMode: Sync
  resources:
  - apiVersion: monitoring.openshift.io/v1alpha1
    kind: ClusterUrlMonitor
    metadata:
      name: api
      namespace: openshift-route-monitor-operator
    spec:
      prefix: https://api.
      port: '6443'
      suffix: /livez
      slo:
        targetAvailabilityPercent: '99.0'
  - apiVersion: monitoring.openshift.io/v1alpha1
    kind: RouteMonitor
    metadata:
      name: console
      namespace: openshift-route-monitor-operator
    spec:
      route:
        name: console
        namespace: openshift-console
      slo:
        targetAvailabilityPercent: '99.5'
