apiVersion: hive.openshift.io/v1
kind: SelectorSyncSet
metadata:
  labels:
    managed.openshift.io/gitHash: ${IMAGE_TAG}
    managed.openshift.io/gitRepoName: ${REPO_NAME}
    managed.openshift.io/osd: 'true'
  name: osd-avo-resources-fedramp-vpc-endpoints-us-gov-east-1
spec:
  clusterDeploymentSelector:
    matchLabels:
      api.openshift.com/managed: 'true'
    matchExpressions:
    - key: api.openshift.com/fedramp
      operator: In
      values:
      - 'true'
    - key: hive.openshift.io/cluster-region
      operator: In
      values:
      - us-gov-east-1
    - key: api.openshift.com/private-link
      operator: In
      values:
      - 'true'
  resourceApplyMode: Sync
  resources:
  - apiVersion: avo.openshift.io/v1alpha2
    kind: VpcEndpoint
    metadata:
      name: splunk
      namespace: openshift-security
    spec:
      serviceName: com.amazonaws.vpce.us-gov-east-1.vpce-svc-0838533cd2d6d2b8b
      securityGroup:
        ingressRules:
        - fromPort: 9997
          toPort: 9997
          protocol: tcp
      vpc:
        autoDiscoverSubnets: true
      customDns:
        route53PrivateHostedZone:
          autoDiscoverPrivateHostedZone: true
          record:
            hostname: splunk
            externalNameService:
              name: indexer
