apiVersion: hive.openshift.io/v1
kind: SelectorSyncSet
metadata:
  labels:
    managed.openshift.io/gitHash: ${IMAGE_TAG}
    managed.openshift.io/gitRepoName: ${REPO_NAME}
    managed.openshift.io/osd: 'true'
  name: kubelet-config-version-major-minor
spec:
  clusterDeploymentSelector:
    matchLabels:
      api.openshift.com/managed: 'true'
    matchExpressions:
    - key: hive.openshift.io/version-major-minor
      operator: NotIn
      values:
      - '4.1'
      - '4.2'
      - '4.3'
      - '4.4'
      - '4.5'
      - '4.6'
      - '4.7'
      - '4.8'
  resourceApplyMode: Upsert
  resources:
  - apiVersion: machineconfiguration.openshift.io/v1
    kind: KubeletConfig
    metadata:
      name: custom-kubelet
    spec:
      machineConfigPoolSelector:
        matchExpressions:
        - key: machineconfiguration.openshift.io/mco-built-in
          operator: Exists
      autoSizingReserved: true
