apiVersion: hive.openshift.io/v1
kind: SelectorSyncSet
metadata:
  labels:
    managed.openshift.io/gitHash: ${IMAGE_TAG}
    managed.openshift.io/gitRepoName: ${REPO_NAME}
    managed.openshift.io/osd: 'true'
  name: ccs-dedicated-admins
spec:
  clusterDeploymentSelector:
    matchLabels:
      api.openshift.com/managed: 'true'
    matchExpressions:
    - key: api.openshift.com/extended-dedicated-admin
      operator: NotIn
      values:
      - 'false'
  resourceApplyMode: Sync
  resources:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      labels:
        managed.openshift.io/aggregate-to-dedicated-admins: project
      name: dedicated-admins-manage-operators
    rules:
    - apiGroups:
      - operators.coreos.com
      resources:
      - '*'
      verbs:
      - '*'
  - apiVersion: managed.openshift.io/v1alpha1
    kind: SubjectPermission
    metadata:
      name: dedicated-admins-customer-monitoring
      namespace: openshift-rbac-permissions
    spec:
      subjectKind: Group
      subjectName: dedicated-admins
      permissions:
      - clusterRoleName: dedicated-admins-project
        namespacesAllowedRegex: ^openshift-customer-monitoring$
      - clusterRoleName: admin
        namespacesAllowedRegex: ^openshift-customer-monitoring$
