apiVersion: hive.openshift.io/v1
kind: SelectorSyncSet
metadata:
  labels:
    managed.openshift.io/gitHash: ${IMAGE_TAG}
    managed.openshift.io/gitRepoName: ${REPO_NAME}
    managed.openshift.io/osd: 'true'
  name: rosa-oauth-templates
spec:
  clusterDeploymentSelector:
    matchLabels:
      api.openshift.com/managed: 'true'
    matchExpressions:
    - key: api.openshift.com/product
      operator: In
      values:
      - rosa
  resourceApplyMode: Upsert
  applyBehavior: CreateOrUpdate
  resources:
  - apiVersion: config.openshift.io/v1
    kind: OAuth
    metadata:
      name: cluster
    spec:
      templates:
        login:
          name: rosa-oauth-templates-login
        providerSelection:
          name: rosa-oauth-templates-providers
        error:
          name: rosa-oauth-templates-errors
