apiVersion: hive.openshift.io/v1
kind: SelectorSyncSet
metadata:
  labels:
    managed.openshift.io/gitHash: ${IMAGE_TAG}
    managed.openshift.io/gitRepoName: ${REPO_NAME}
    managed.openshift.io/osd: 'true'
  name: backplane-lpsre-hypershift-management-cluster
spec:
  clusterDeploymentSelector:
    matchLabels:
      api.openshift.com/managed: 'true'
    matchExpressions:
    - key: ext-hypershift.openshift.io/cluster-type
      operator: In
      values:
      - management-cluster
    - key: api.openshift.com/fedramp
      operator: NotIn
      values:
      - 'true'
  resourceApplyMode: Sync
  resources:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: backplane-lpsre-management-cluster-project
    rules:
    - apiGroups:
      - package-operator.run
      resources:
      - '*'
      verbs:
      - get
      - list
      - watch
      - update
      - patch
      - create
      - delete
  - apiVersion: managed.openshift.io/v1alpha1
    kind: SubjectPermission
    metadata:
      name: backplane-lpsre-management-cluster
      namespace: openshift-rbac-permissions
    spec:
      permissions:
      - clusterRoleName: admin
        namespacesAllowedRegex: (^openshift-package-operator$)
      - clusterRoleName: backplane-lpsre-management-cluster-project
        namespacesAllowedRegex: (^ocm-.*|^openshift-package-operator$)
      subjectKind: Group
      subjectName: system:serviceaccounts:openshift-backplane-lpsre
