apiVersion: hive.openshift.io/v1
kind: SelectorSyncSet
metadata:
  labels:
    managed.openshift.io/gitHash: ${IMAGE_TAG}
    managed.openshift.io/gitRepoName: ${REPO_NAME}
    managed.openshift.io/osd: 'true'
  name: backplane-lpsre-acm
spec:
  clusterDeploymentSelector:
    matchLabels:
      api.openshift.com/managed: 'true'
      api.openshift.com/addon-advanced-cluster-management: 'true'
  resourceApplyMode: Sync
  resources:
  - apiVersion: managed.openshift.io/v1alpha1
    kind: SubjectPermission
    metadata:
      name: backplane-lpsre-acm-admins-project
      namespace: openshift-rbac-permissions
    spec:
      permissions:
      - clusterRoleName: view
        namespacesAllowedRegex: (^redhat-open-cluster-management$)
      - clusterRoleName: backplane-lpsre-acm-admins-project
        namespacesAllowedRegex: (^redhat-open-cluster-management$)
      subjectKind: Group
      subjectName: system:serviceaccounts:openshift-backplane-lpsre
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: backplane-acm-lpsre-admins-project
    rules:
    - apiGroups:
      - addon.open-cluster-management.io
      - apps.open-cluster-management.io
      - cluster.open-cluster-management.io
      - clusterview.open-cluster-management.io
      - discovery.open-cluster-management.io
      - imageregistry.open-cluster-management.io
      - inventory.open-cluster-management.io
      - monitor.open-cluster-management.io
      - observability.open-cluster-management.io
      - operator.open-cluster-management.io
      - proxy.open-cluster-management.io
      - search.open-cluster-management.io
      - submarineraddon.open-cluster-management.io
      - work.open-cluster-management.io
      resources:
      - '*'
      verbs:
      - get
      - list
      - watch
